spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true  #이건 꽤 재밌는건데, paging처리는 0부터 시작인데 이걸 해두면 1부터 시작함.
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        show_sql: true

  datasource:
    url: jdbc:h2:mem:in2l
    username: sa
    password:
    driver-class-name: org.h2.Driver

#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/Database/in2l
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#
#logging.level:
#  org.hibernate.SQL: debug
##  org.hibernate.type: trace